#!/usr/bin/env perl
# Copyright (C) 2014 Tony Crisci <tony@dubstepdish.com>
# Copyright (C) 2015 Thiago Perrotta <perrotta dot thiago at poli dot ufrj dot br>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# For all media players except mpd/cmus/rhythmbox, MPRIS support should be
# enabled and the playerctl binary should be in your path.
# See https://github.com/acrisci/playerctl

# Set instance=NAME in the i3blocks configuration to specify a music player
# (playerctl will attempt to connect to org.mpris.MediaPlayer2.[NAME] on your
# DBus session). If instance is empty, playerctl will connect to the first
# supported media player it finds.

my $player_arg = "playerctl -p ncspot";
my @metadata = ();

sub playerctl {
    my $status = qx($player_arg status 2>/dev/null);
    chomp $status;
    if ($status ne "Playing") {
        return
    }

    my $artist = qx($player_arg metadata artist 2>/dev/null);
    chomp $artist;
    # exit status will be nonzero when playerctl cannot find your player
    exit(0) if $? || $artist eq '(null)';

    #$artist =~ s/&/and/ig;

    push(@metadata, $artist) if $artist;

    my $title = qx($player_arg metadata title);
    exit(0) if $? || $title eq '(null)';
    $title =~ s/&/and/ig;

    push(@metadata, $title) if $title;
    
    print(join(" - ", @metadata)) if @metadata;
}

playerctl
